AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application for deploying the Medium scraper.
Parameters:
  BucketName:
    Description: Name of the S3 bucket
    Type: String
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: scrape-medium-articles
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./code/.
      Description: Call the AWS Lambda API
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: !Sub "arn:aws:s3:::${BucketName}/*"
      Tracing: Active
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: medium-scraper-lib
      Description: Dependencies for the Medium scraper app.
      ContentUri:
        Bucket: !Ref BucketName
        Key: package.zip
      CompatibleRuntimes:
        - python3.8
